### ISSUE TITLE
Bug in predict with subject_specific ?

### ISSUE THREAD

**Issue by florianhartig** [drizopoulos/GLMMadaptive#12]
Tried to implement the residuals for  https://github.com/drizopoulos/GLMMadaptive/issues/11, but realised that predict works with mean_subject, but not subject_specific ... is this a bug, or is there a reason why this wouldn't work?

```
> predict(fittedModel, type_pred = "response", type = "subject_specific")
Error: object of type 'closure' is not subsettable
```

**Comment by drizopoulos** [comment]
Thanks! This should now be resolved.
