### ISSUE TITLE
Relationship between mixed_model and hurdle model from pscl package

### ISSUE THREAD

**Issue by sfaridimehr** [drizopoulos/GLMMadaptive#17]
The hurdle model from pscl package gives this option to predict response, count, probability and zero (which is the ratio that is multiplied by count and gives response). Does "zero_part" from GLMMadaptive package give probability from Poisson or probability from binary logistic regression?

**Comment by drizopoulos** [comment]
The call `predict(..., type = "zero_part")` will return you predictions for the log odds (if `type_pred = "link"`) or the probability (if `type_pred = "response"`) for a zero count coming from the degenerate distribution at zero (i.e., *not* from the Poisson distribution). Note, that these log odds or probabilities are based only on the fixed effects of the zero_part.

All other option for the `type` argument in `predict()` for zero-inflated or hurdle models give `(1 - pi) * exp_count`, where `pi` is the probability of coming from the degenerate part (i.e., the same as above), and `exp_coint` is the expected counts from the Poisson part.
