### ISSUE TITLE
Allow case-specific weights

### ISSUE THREAD

**Issue by lmwang9527** [drizopoulos/GLMMadaptive#22]
I am using the GLMMadaptive package to estimate a two-part mixed model where my groups are geographical regions but cases from the same region may have different weights. As I can see that GLMMadaptive only allow weights matching with the number of groups, would it be possible to use case-specific weights? That is, the length of weights matches the number of rows of data. Thanks!

Also, thanks for creating such a helpful package!

**Comment by drizopoulos** [comment]
Indeed, the weights now are simple multipliers on the log-likelihood contributions of each group/cluster. It is not clear to me how this could be extended theoratically in the observations level.
