### ISSUE TITLE
resids_plot for beta family

### ISSUE THREAD

**Issue by TPERRIN684** [drizopoulos/GLMMadaptive#27]
Hello,

I first applied the mixed model with the custom beta family available in your website to the data.

![model](https://user-images.githubusercontent.com/62617716/77463824-8517a580-6e06-11ea-9b55-62303d3cfeda.png)

Then I tried to use the function resids_plot available in your website:

![resid_plot](https://user-images.githubusercontent.com/62617716/77465366-c6a95000-6e08-11ea-8576-7d8c785531dd.png)

I get this error message when I use it:

![resid](https://user-images.githubusercontent.com/62617716/77465622-391a3000-6e09-11ea-96e6-afb906bfce0c.png)

![erreur](https://user-images.githubusercontent.com/62617716/77464430-7087dd00-6e07-11ea-8e6e-ecc44c51bed4.png)

The problem seems to come from the arguments of the function ![simulate](https://user-images.githubusercontent.com/62617716/77464651-cd839300-6e07-11ea-9f83-6bd3a4ff34dc.png). 
Do I need to change them ?

Thanks,
Thomas

**Comment by drizopoulos** [comment]
Try the build-in beta family object.

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________
