### ISSUE TITLE
how to use the predict function with Gaussian mixed model

### ISSUE THREAD

**Issue by Mathematinho** [drizopoulos/GLMMadaptive#29]
when i have a merMod object from lmer, is there a way i can utilize the predict.MixMod function for dynamic subject-specific predictions?

**Comment by drizopoulos** [comment]
No, this is not possible.

——
Professor of Biostatistics
Erasmus Medical Center Rotterdam
The Netherlands
________________________________
Από: Mathematinho <notifications@github.com>
Στάλθηκε: Wednesday, October 21, 2020 5:05:25 PM
Προς: drizopoulos/GLMMadaptive <GLMMadaptive@noreply.github.com>
Κοιν.: Subscribed <subscribed@noreply.github.com>
Θέμα: [drizopoulos/GLMMadaptive] how to use the predict function with Gaussian mixed model (#29)


when i have a merMod object from lmer, is there a way i can utilize the predict.MixMod function for dynamic subject-specific predictions?
