### ISSUE TITLE
Discussion: Model Selection with GLMMadaptive 

### ISSUE THREAD

**Issue by mamscience** [drizopoulos/GLMMadaptive#30]
Dear dr. Rizopoulos

Thanks for writing GLMMadaptive. It's been intuitive to work with, even for somebody who's new to GLMM like myself.

My question is regarding model selection: What approach would you advice in model selection? In your vignette Goodness of Fit you suggest using DHARMa to aid in the selection. With binomial models, only the residuals vs fitted graph is useful to assess fitness. I believe that this is hard,  particularly when all models do not fit perfectly.  Can you suggest more tools or approaches for selecting models?

Kind regards, Michel

**Comment by drizopoulos** [comment]
Dear Michel,

If you want to compare between models (i.e., this is what I understand with “model selection”), you can use a likelihood ratio test if the models are nested or look at the information criteria AIC and BIC if the models are not nested. Both are available in the anova() function.

Best,
Dimitris

**Comment by mamscience** [comment]
Thanks for your reply. 
I've read in multiple articles saying that using AIC/BIC should be used with caution with GLMM, but I understand from your reply that this is not the case for non-nested models. 

I had a follow-up question: How would you choose between a model that has a better AIC fit but a worse resid vs fitted plot, compared to a model that has a worse AIC but better resid/fitted plot?

**Comment by drizopoulos** [comment]
This question is more about statistics rather than about the functionality of the package.
