### ISSUE TITLE
Implement a refit function

### ISSUE THREAD

**Issue by florianhartig** [drizopoulos/GLMMadaptive#32]
Hi Dimitris,

I am currently making another attempt to integrate GLMMadaptive to DHARMa, see https://github.com/florianhartig/DHARMa/issues/96

One point that I noted is that GLMMadaptive does not have a refit function, as in https://www.rdocumentation.org/packages/lme4/versions/1.1-26/topics/refit

I tried to circumvent this via the following code 

getRefit.MixMod <- function(object, newresp, ...) {
  responsename = colnames(model.frame(object))[1] 
  newDat = object$data
  newDat[, match(responsename,names(newDat))] = newresp
  update(object, data = newDat)
}

The issue with that is that this fails for k/n binomial with c(s,f) ~ pred syntax

Any great idea how to solve this with a quick hack that is not super hacky, or do you see an option to supply a refit function in GLMMadaptive?

**Comment by drizopoulos** [comment]
Hi Florian,

Thanks for taking this up. I will have a look and let you know how this could be done.

However, it is not clear to me why you need to refit the model. This will be computationally expensive. My understanding was that you only need to simulate from the model. At least, this is how I use your package in the custom made function  resids_plot() I have here: https://drizopoulos.github.io/GLMMadaptive/articles/Goodness_of_Fit.html

Best,
Dimitris

**Comment by florianhartig** [comment]
Hi Dimitris,

for historical reasons, I'm still carrying around 2 versions of calculating everything in DHARMa, 

1) where quantile residuals are created by comparing observed vs. simulated data (default)
2) where the models are re-fit to the simulated data, and residuals or other properties of the model are compared 

The original motivation for this was the idea that option 2 would be more reliable for biased estimators. In practice, I have found few advantages of the refit, but for the moment I'm keeping the option.

More generally though, the refit is important for parametric bootstrap and all that.

**Comment by drizopoulos** [comment]
Hi Florian,

I have written a short `refit()` function that seems to do the trick - see below:

```
# simulate some data
set.seed(123L)
n <- 500
K <- 15
t.max <- 25

betas <- c(-2.13, -0.25, 0.24, -0.05)
D <- matrix(0, 2, 2)
D[1:2, 1:2] <- c(0.48, -0.08, -0.08, 0.18)

times <- c(replicate(n, c(0, sort(runif(K-1, 0, t.max)))))
group <- sample(rep(0:1, each = n/2))
DF <- data.frame(year = times, group = factor(rep(group, each = K)))
X <- model.matrix(~ group * year, data = DF)
Z <- model.matrix(~ year, data = DF)

b <- cbind(rnorm(n, sd = sqrt(D[1, 1])), rnorm(n, sd = sqrt(D[2, 2])))
id <- rep(1:n, each = K)
eta.y <- as.vector(X %*% betas + rowSums(Z * b[id, ]))
DF$y <- rbinom(n * K, 10, plogis(eta.y))
DF$fails <- 10 - DF$y
DF$id <- factor(id)

################################################################
################################################################

fm <- mixed_model(fixed = cbind(y, fails) ~ year * group, 
                  random = ~ 1 | id, data = DF,
                  family = binomial())

refit_MixMod <- function (object, newresp = NULL) {
    if (is.null(newresp)) return(object)
    if (!is.data.frame(newresp)) stop("'newresp' must be a data.frame.")
    newdata <- object$data
    respVars <- all.vars(update.formula(formula(object), . ~ 0))
    newdata[respVars] <- newresp[respVars]
    update(object, data = newdata)
}

fm
refit_MixMod(fm, DF)
```
