### ISSUE TITLE
Possibility to evaluate marginal log-likelihood

### ISSUE THREAD

**Issue by sebastianueckert** [drizopoulos/GLMMadaptive#35]
Hi Dimitris,

Thanks a lot for your work on this very useful package. 

I would like to use `GLMMadaptive` to calculate a cross-validated log-likelihood, i.e., to estimate model parameters using a subset of the observations and then evaluate the marginal log-likelihood for the hold-out set. I was, therefore, wondering if it is possible to do the integration in `GLMMadaptive` without any optimization?

Sebastian

**Comment by drizopoulos** [comment]
Hi Sebastian,

Yes, this is possible by setting iter_EM and iter_qN_outer to zero.

Dimitris

——
Professor of Biostatistics
Erasmus Medical Center Rotterdam
The Netherlands
________________________________
Από: Sebastian Ueckert ***@***.***>
Στάλθηκε: Tuesday, March 30, 2021 12:27:56 PM
Προς: drizopoulos/GLMMadaptive ***@***.***>
Κοιν.: Subscribed ***@***.***>
Θέμα: [drizopoulos/GLMMadaptive] Possibility to evaluate marginal log-likelihood (#35)


Hi Dimitris,

Thanks a lot for your work on this very useful package.

I would like to use GLMMadaptive to calculate a cross-validated log-likelihood, i.e., to estimate model parameters using a subset of the observations and then evaluate the marginal log-likelihood for the hold-out set. I was, therefore, wondering if it is possible to do the integration in GLMMadaptive without any optimization?

Sebastian

**Comment by sebastianueckert** [comment]
Thanks a lot!
