### ISSUE TITLE
Error in chol.default(X[[i]], ...) 

### ISSUE THREAD

**Issue by Ivy-ops** [drizopoulos/GLMMadaptive#36]
Hi developer, 

Thanks for creating this package. 
I encounter below error when running  below code. May I please have your help? Thanks!!

`gm1 <- mixed_model(fixed = taxon ~ X + time, random = ~ time|SubjectID, data = df, family=zi.negative.binomial(), zi_fixed = ~ 1)`

```
Error in chol.default(X[[i]], ...) : 
  the leading minor of order 1 is not positive definite
```

**Comment by drizopoulos** [comment]
Without a reproducible example, I cannot see what is going wrong.
