### ISSUE TITLE
Documentation contains dead links

### ISSUE THREAD

**Issue by cgeger** [drizopoulos/GLMMadaptive#38]
Hello Sir,
I would like to try using a hurdle or censored.normal GLMMadaptive mixed model, but the help links for the package in the RStudio documentation pane return an error, and there are several documentation pages with dead links on the package website. This is just a general message to call your attention to it, since you may not be aware that the documentation is not accessible.

Thank you,
Caitlin

**Comment by drizopoulos** [comment]
Thanks, I will look it up.
