### ISSUE TITLE
May I know how to get the effect size of a two-part mixed effects model?

### ISSUE THREAD

**Issue by ZZZZZch** [drizopoulos/GLMMadaptive#39]
Hello Prof Dimitris Rizopoulos,

Many thanks for developing such a great tool for us.

I'm developing a two-part mixed effects model for semi-continuous data. May I know how to get the effect size of the model? Maybe just like conditional or marginal R square for general mixed effects models?

Have a blessed 2022!

Chenghao

**Comment by drizopoulos** [comment]
Hi, it isn’t clear what you mean by effect size in such a model.

——
Professor of Biostatistics
Erasmus Medical Center Rotterdam
The Netherlands
________________________________
Από: Vickers Zhu ***@***.***>
Στάλθηκε: Friday, January 7, 2022 9:46:10 AM
Προς: drizopoulos/GLMMadaptive ***@***.***>
Κοιν.: Subscribed ***@***.***>
Θέμα: [drizopoulos/GLMMadaptive] May I know how to get the effect size of a two-part mixed effects model? (Issue #39)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hello Prof Dimitris Rizopoulos,

Many thanks for developing such a great tool for us.

I'm developing a two-part mixed effects model for semi-continuous data. May I know how to get the effect size of the model? Maybe just like conditional or marginal R square for general mixed effects models?

Have a blessed 2022!

Chenghao

**Comment by ZZZZZch** [comment]
Hi Prof, 

Sorry for my unclear expression.

I notice that in many research papers, when using a general mixed-effect model, they would introduce how the quality of their model was assessed, like reporting the percentage of correctly predicted observations, calculating the value of marginal and conditional R2, or comparing the BIC or AIC values with those of a null model.

When using GLMMadaptive to fit a two-part mixed-effects model, what kind of way you may recommend evaluating the quality of the models?

Chenghao

**Comment by drizopoulos** [comment]
I’m not aware of an R^2 for two-part models, but the AIC and BIC are calculated in the package.


________________________________
Από: Vickers Zhu ***@***.***>
Στάλθηκε: Friday, January 7, 2022 2:09:59 PM
Προς: drizopoulos/GLMMadaptive ***@***.***>
Κοιν.: Dimitris Rizopoulos ***@***.***>; Comment ***@***.***>
Θέμα: Re: [drizopoulos/GLMMadaptive] May I know how to get the effect size of a two-part mixed effects model? (Issue #39)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



Hi Prof,

Sorry for my unclear expression.

I notice that in many research papers, when using a general mixed-effect model, they would introduce how the quality of their model was assessed, like reporting the percentage of correctly predicted observations, calculating the value of marginal and conditional R2, or comparing the BIC or AIC values with those of a null model.

When using GLMMadaptive to fit a two-part mixed-effects model, what kind of way you may recommend evaluating the quality of the models?

Chenghao

**Comment by ZZZZZch** [comment]
Thank you Prof Rizopoulos, then I'll report AICs and BIC in paper first. Many thanks again.
