### ISSUE TITLE
Adding "sandwich" argument to mixed_model

### ISSUE THREAD

**Issue by blinthwaite** [drizopoulos/GLMMadaptive#41]
Would it be possible to have the `sandwich` argument added directly to the `mixed_model` function, rather than as an additional argument in standard generic functions (`summary`, `vcov`, `confint`, etc.). 

This would allow for compatibility with `broom.mixed` and integration into a tidy workflow. 

Love the package, thanks in advance!

**Comment by drizopoulos** [comment]
Thanks for the suggestion. I will consider it for the next release.
