### ISSUE TITLE
Error: No glance method for objects of class MixMod

### ISSUE THREAD

**Issue by reiniervlinschoten** [drizopoulos/GLMMadaptive#42]
Hi,

I am trying to work with multiply imputed data and the GLMMAdaptive package.
However, it seems that the glance() method is missing for MixMod objects, which complicates pooling and testing of model parameters over multiply imputed data. Is there a glance() method for MixMod in any package?

Kind regards,
Reinier

**Comment by reiniervlinschoten** [comment]
There seem to be experimental functions in [broom.mixed](https://github.com/bbolker/broom.mixed), but these don't seem to work?

**Comment by drizopoulos** [comment]
I’m not aware of any package offering this.

——
Professor of Biostatistics
Erasmus Medical Center Rotterdam
The Netherlands
________________________________
Από: Reinier van Linschoten ***@***.***>
Στάλθηκε: Thursday, April 28, 2022 9:05:44 AM
Προς: drizopoulos/GLMMadaptive ***@***.***>
Κοιν.: Subscribed ***@***.***>
Θέμα: Re: [drizopoulos/GLMMadaptive] Error: No glance method for objects of class MixMod (Issue #42)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



There seem to be experimental functions in broom.mixed<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbbolker%2Fbroom.mixed&data=05%7C01%7Cd.rizopoulos%40erasmusmc.nl%7Cc050b7bc59ae49dc7dbf08da28e5841d%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C0%7C637867263483371374%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OkZ90hpe9Sfks2JlRjPKSUaHhnXN9CG4tVoxiNjHjcM%3D&reserved=0>, but these don't seem to work?

**Comment by reiniervlinschoten** [comment]
Thank you for the quick response. Is there any way to extract the residual df from a MixMod object?

**Comment by drizopoulos** [comment]
AFAIK, residual degrees of freedom are not that easily defined in general mixed-effects models settings.

**Comment by reiniervlinschoten** [comment]
Yeah, I ran into that too, maybe a temporary workaround can be added to allow functionality that depends on residual degrees of freedom?

For example from the [glmmTMB package](https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/R/methods.R)?
(Don't know if this is an acceptable solution, but this would allow the package to be used with for example MICE).

```R
##' @importFrom stats df.residual
##' @method df.residual glmmTMB
##' @export
##  TODO: not clear whether the residual df should be based
##  on p=length(beta) or p=length(c(theta,beta)) ... but
##  this is just to allow things like aods3::gof to work ...
##  Taken from LME4, including the todo
##
df.residual.glmmTMB <- function(object, ...) {
  nobs(object)-length(object$fit$par)
}
```

**Comment by drizopoulos** [comment]
Perhaps it would allow it to work with MICE, but the relevant questions are where these degrees of freedom will be used and whether giving these degrees of freedom may lead to incorrect results.
