### ISSUE TITLE
hurdle.lognormal() needs to trigger error message when zi_fixed is omitted

### ISSUE THREAD

**Issue by edseab** [drizopoulos/GLMMadaptive#48]
In the mixed_model function,  this early if statement:

   if (family$family %in% c("zero-inflated poisson", "zero-inflated negative binomial",
        "hurdle poisson", "hurdle negative binomial", "hurdle beta",
        "zero-inflated binomial") && is.null(zi_fixed)) {
        stop("you have defined a family with an extra zero-part;\nat least argument ",
            "'zi_fixed' needs to be defined, and potentially also argument 'zi_random'.")
    }

should also include the hurdle lognormal family. Otherwise omitting zi_fixed leads to this confusing error:

'data' must be of a vector type, was 'NULL'

Thanks!

**Comment by drizopoulos** [comment]
Thanks for reporting. The corrected version is on GitHub now.
