### ISSUE TITLE
More than one random effect?

### ISSUE THREAD

**Issue by datalorax** [drizopoulos/GLMMadaptive#50]
Sorry to post an issue for a question. My question is equivalent to [this](https://stackoverflow.com/questions/77382180/how-to-specify-two-random-intercepts-in-random-argument-of-mixed-model-funct) stackoverflow post. Is it possible to use GLMMadaptive with more than one random effect? For example, with lme4 I might fit a model like

``` r
d <- ltm::LSAT
d$respondent <- seq_len(nrow(d))
d <- tidyr::pivot_longer(
  d,
  -respondent,
  names_to = "item",
  values_to = "response"
)

m <- lme4::glmer(
  response ~ 1 + (1 | respondent) + (1 | item),
  data = d,
  family = binomial(link = "logit")
)
```

Is this model possible with GLMMadaptive?

**Comment by drizopoulos** [comment]
Unfortunately, this is not possible.

**Comment by datalorax** [comment]
Okay, thanks for the reply.
