### ISSUE TITLE
A binomial model with log link function doesn't display summary

### ISSUE THREAD

**Issue by scherbakovdmitri** [drizopoulos/GLMMadaptive#53]
Hello all, thanks for helpful package, glmer didn't converge, I am glad I found yours. But I have a problem, here is my model

`m2=GLMMadaptive::mixed_model(fixed=screen.completed~Variable
                          ,control = list(#max_coef_value=1000,iter_EM=1000,iter_qN_outer=1000,
                                         verbose=T,
                                         #iter_qN=100,
                                         update_GH_every=40
                                         ),
                          random=~1|Department,
                          na.action=na.fail,
                          data=data
                          ,family=binomial(link='log')
)`

when I view summary I get error, so how do I plot confidence intervals for coefficients? Looks like the problem is only with log link function.

`summary(m2)
Error in solve.default(object$Hessian) : 
  Lapack routine dgesv: system is exactly singular: U[1,1] = 0`

**Comment by drizopoulos** [comment]
The model has not successfully converged.
