### ISSUE TITLE
weights in mixed_model()?

### ISSUE THREAD

**Issue by strengejacke** [drizopoulos/GLMMadaptive#6]
Is it possible to use weights in `mixed_model()`? I haven't found anything in the help files.

**Comment by drizopoulos** [comment]
No, weights have not been implemented yet. Do you want to use them for 
specific purposes?



On 1/21/2019 5:54 PM, Daniel wrote:
> Is it possible to use weights in |mixed_model()|? I haven't found 
> anything in the help files.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdrizopoulos%2FGLMMadaptive%2Fissues%2F6&data=02%7C01%7Cd.rizopoulos%40erasmusmc.nl%7Ce0c13d08228d41ef762708d67fc11b24%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C1%7C636836864694431260&sdata=1R8F2tCsgqSzgETnBrzH9QdbQhn9iKeLqLvl%2BQ0PYIo%3D&reserved=0>, 
> or mute the thread 
> <https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAMn5z9FUcikfV1iY8YNkiokURJ7CJLK1ks5vFfDCgaJpZM4aLM0a&data=02%7C01%7Cd.rizopoulos%40erasmusmc.nl%7Ce0c13d08228d41ef762708d67fc11b24%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C1%7C636836864694431260&sdata=QTGRtM2UDd%2B7Hx35gzmj6gRL8m05deAXrirtzRw1K40%3D&reserved=0>.
> 

-- 
Dimitris Rizopoulos
Professor of Biostatistics
Department of Biostatistics
Erasmus University Medical Center

Address: PO Box 2040, 3000 CA Rotterdam, the Netherlands
Tel: +31/(0)10/7043478
Fax: +31/(0)10/7043014
Web (personal): http://www.drizopoulos.com/
Web (work): http://www.erasmusmc.nl/biostatistiek/
Blog: http://iprogn.blogspot.nl/

**Comment by strengejacke** [comment]
Sometimes, e.g. in case of panel attrition, we use response propensity weights in our models. Or in case of analyzing survey-data, you may have a weighting-variable that can be used in standard regression or mixed models, without the need for a specific survey design.

**Comment by strengejacke** [comment]
Two surveys come to my mind where weights are required, e.g. when using mixed models to analyse the data: European Social Survey and German Ageing Survey.

Would you say it's difficult to implement such a feature?

**Comment by drizopoulos** [comment]
A `weights` argument has been added in `mixed_model()`. These are simple multipliers on the log-likelihood contributions of each group/cluster, i.e., we presume that there are multiple replicates of each group/cluster denoted by the weights.

**Comment by strengejacke** [comment]
btw, you have changed the structure of how the model frames (like `x$model_frames$mfX_zi`) are saved in MixMod-objects with the last update? Is there a reason for this?

**Comment by drizopoulos** [comment]
Yes, because I’m working on the extension to nested random effects.

**Comment by strengejacke** [comment]
ok, thanks! It broke the _insight_ pkg on CRAN, but the issue is already fixed and I'm planning to submit soon.
