### ISSUE TITLE
predict() has no default for newdata?

### ISSUE THREAD

**Issue by florianhartig** [drizopoulos/GLMMadaptive#8]
Hi Dimitris, as you know, I'm trying to integrate GLMMadative in DHARMa.

I'm currently fighting with a somewhat surprising behavior of your predict() function - is it so that predict requires newdata? My expectation from other packages would have been that the function would fall back on the fit data if newdata is not provided, so that you could do, e.g.

```
fm1 <- mixed_model(fixed = y ~ year * group, random = ~ 1 | id, data = DF,
                   family = binomial())
predict(fm1) 
```

**Comment by drizopoulos** [comment]
Thanks! This should now work in GLMMadaptive_0.4-9999999.

**Comment by florianhartig** [comment]
yes, thanks! Side comment: I find it a bit confusing that the S3 methods in GLMMadaptive deviate so strongly from most other packages, e.g. that the usual type = "response" etc. can't be used in this way. One can find out from the help of course, but it isn't very intuitive for a new user.

Not sure if it's worth switching now though.

**Comment by drizopoulos** [comment]
I'm aware of that, but to maintain consistency with the use of the `type` argument in other functions in the package, I decided to do it like this. I can understand that this may cause issues, but I hope that it is well-documented.
