### ISSUE TITLE
mixed_model() fails for example model from glmer()-docs

### ISSUE THREAD

**Issue by strengejacke** [drizopoulos/GLMMadaptive#9]
No idea where to locae the source from this error, but this rather simple looking model fails to fit with `mixed_model()`. Any ideas, why?

``` r
library(GLMMadaptive)
library(lme4)

m1 <- glmer(
  cbind(incidence, size - incidence) ~ period + (1 | herd), 
  data = cbpp, 
  family = binomial
)

m2 <- mixed_model(
  cbind(incidence, size - incidence) ~ period,
  random = ~ 1 | herd,
  data = cbpp, 
  family = binomial
)
#> Error in -(X * if (NCOL(y) == 2) y[, 1] else y) + sc: non-conformable arrays
```

<sup>Created on 2019-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by drizopoulos** [comment]
Thanks! This should now work in GLMMadaptive_version 0.4-9999999.
